//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class abuse_assessment
    {
        public int PatientID { get; set; }
        public string AbuseType { get; set; }
        public string Issue { get; set; }
        public string AgeOfAbuse { get; set; }
        public string AbuserName { get; set; }
        public string AbusedTime { get; set; }
        public string Reported { get; set; }
        public string ReportedToWhom { get; set; }
        public string CY47Complete { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
