using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ExampleLook
{
    public partial class AdultSocialWorkWindow : Form
    {
        public AdultSocialWorkWindow()
        {
            InitializeComponent();
        }

        private void patient_admission_extBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.patient_admission_extBindingSource.EndEdit();
            this.tableAdapterManager.UpdateAll(this.cPCAppDataSet);

        }

        private void AdultSocialWorkWindow_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'cPCAppDataSet.substance_abuse' table. You can move, or remove it, as needed.
            this.substance_abuseTableAdapter.Fill(this.cPCAppDataSet.substance_abuse);
            // TODO: This line of code loads data into the 'cPCAppDataSet.family_members' table. You can move, or remove it, as needed.
            this.family_membersTableAdapter.Fill(this.cPCAppDataSet.family_members);
            // TODO: This line of code loads data into the 'cPCAppDataSet.patient_admission' table. You can move, or remove it, as needed.
            this.patient_admissionTableAdapter.Fill(this.cPCAppDataSet.patient_admission);
            // TODO: This line of code loads data into the 'cPCAppDataSet.patient_admission_ext' table. You can move, or remove it, as needed.
            this.patient_admission_extTableAdapter.Fill(this.cPCAppDataSet.patient_admission_ext);

        }

        //private void setAdultSocialWork()
        //{
        //    dl.aSWAssignWorker = aSWAssignWorkerTextBox.Text;
        //    dl.powAttorneyLName = powAttorneyLNameTextBox.Text;
        //    dl.powAttorneyFName = powAttorneyFNameTextBox.Text;
        //    dl.guardianshipLName = guardianshipLNameTextBox.Text;
        //    dl.guardianshipFName = guardianshipFNameTextBox.Text;
        //    dl.lastName = lastNameTextBox.Text;
        //    dl.firstName = firstNameTextBox.Text;
        //    dl.aSWDateComplete = aSWDateCompleteDateTimePicker.Value;
        //    dl.assessStartDate = assessStartDateDateTimePicker.Value;
        //    dl.aSWCommInvolve = aSWCommInvolveTextBox.Text;
        //    dl.aSWFamSupDesc = aSWFamSupDescPatTextBox.Text;
        //    dl.aSWPatDescSelfSomeone = aSWPatDescSelfSomeoneTextBox.Text;
        //    dl.aSWCurLevFuncDifTypFunc = aSWCurLevFuncDifTypFuncTextBox.Text;
        //    dl.aSWNaturePresProb = aSWNaturePresProbTextBox.Text;
        //    dl.aSWReliableSrcDesc = aSWReliableSrcDescTextBox.Text;
        //    dl.aSWSrcInfo = aSWSrcInfoTextBox.Text;
        //    dl.aSWLegStatDesc = aSWLegStatDescTextBox.Text;
        //    dl.aSWDangerSelfIntent = aSWDangerSelfIntentCheckBox.Checked;
        //    dl.aSWDangerSelfAttempt = aSWDangerSelfAttemptCheckBox.Checked;
        //    dl.aSWDangerSelfPlan = aSWDangerSelfPlanCheckBox.Checked;
        //    dl.aSWDangerSelfIdeation = aSWDangerSelfIdeationCheckBox.Checked;
        //    dl.aSWDangerSelfHistory = aSWDangerSelfHistoryCheckBox.Checked;
        //    dl.aSWDangerSelfCurrent = aSWDangerSelfCurrentCheckBox.Checked;
        //    dl.aSWDangerSelfNotPres = aSWDangerSelfNotPresCheckBox.Checked;
        //    dl.aSWWeaponLethMeansRemovePlan = aSWWeaponLethMeansRemovePlanTextBox.Text;
        //    dl.aSWPastSelfInjDesc = aSWPastSelfInjDescTextBox.Text;
        //    dl.aSWLethPriorMeans = aSWLethPriorMeansTextBox.Text;
        //    dl.aSWDangerDesc = aSWDangerDescTextBox.Text;
        //    dl.aSWDangerOthersNotPres = aSWDangerOthersNotPresCheckBox.Checked;
        //    dl.aSWDangerOthersIntent = aSWDangerOthersIntentCheckBox.Checked;
        //    dl.aSWDangerOthersAttempt = aSWDangerOthersAttemptCheckBox.Checked;
        //    dl.aSWDangerOthersPlan = aSWDangerOthersPlanCheckBox.Checked;
        //    dl.aSWDangerOthersIdeation = aSWDangerOthersIdeationCheckBox.Checked;
        //    dl.aSWDangerOthersHistory = aSWDangerOthersHistoryCheckBox.Checked;
        //    dl.aSWDangerOthersCurrent = aSWDangerOthersCurrentCheckBox.Checked;
        //    dl.aSWVerifyTime = aSWVerifyTimeTextBox.Text;
        //    dl.aSWVerifyDate = aSWVerifyDateDateTimePicker.Value;
        //    dl.aSWVerify = aSWVerifyTextBox.Text;
        //    dl.aSWResponsePatTime = aSWResponsePatTimeTextBox.Text;
        //    dl.aSWResponsePatDate = aSWResponsePatDateDateTimePicker.Value;
        //    dl.aSWResponsePat = aSWResponsePatTextBox.Text;
        //    dl.aSWEmoNegAbuseReportedDesc = aSWEmoNegAbuseReportedDescTextBox.Text;
        //    dl.aSWEmoNegAbuseWitnessDesc = aSWEmoNegAbuseWitnessDescTextBox.Text;
        //    dl.aSWPhsyAbuseReportDesc = aSWPhsyAbuseReportDescTextBox.Text;
        //    dl.aSWPhsyAbuseWitnessDesc = aSWPhsyAbuseWitnessDescTextBox.Text;
        //    dl.aSWSexAbuseReportDesc = aSWSexAbuseReportDescTextBox.Text;
        //    dl.aSWSexAbuseWitnessDesc = aSWSexAbuseWitnessDescTextBox.Text;
        //    dl.aSWOtherTraumaExp = aSWOtherTraumaExpTextBox.Text;
        //    dl.aSWTermPregDesc = aSWTermPregDescTextBox.Text;
        //    dl.aSWDateChange = aSWDateChangeDateTimePicker.Value;
        //    dl.aSWSafeHomeDesc = aSWSafeHomeDescTextBox.Text;
        //    dl.aSWHomePlanDisch = aSWHomePlanDischTextBox.Text;
        //    dl.aSWRetHomeWhen = aSWRetHomeWhenTextBox.Text;
        //    dl.aSWRetHomeWhom = aSWRetHomeWhomTextBox.Text;
        //    dl.aSWHomePrior = aSWHomePriorTextBox.Text;
        //    dl.aSWRecFamInvolve = aSWRecFamInvolveTextBox.Text;
        //    dl.aSWFamDeclineReason = aSWFamDeclineReasonTextBox.Text;
        //    dl.aSWFamSessInvite = aSWFamSessInviteTextBox.Text;
        //    dl.aSWDateFamSess = aSWDateFamSessDateTimePicker.Value;
        //    dl.aSWRelatProb = aSWRelatProbTextBox.Text;
        //    dl.aSWMemHelpfulDesc = aSWMemHelpfulDescTextBox.Text;
        //    dl.aSWPriorFamInvolve = aSWPriorFamInvolveTextBox.Text;
        //    dl.aSWDvlpExplain = aSWDvlpExplainTextBox.Text;
        //    dl.aSWDvlpOtherDesc = aSWDvlpOtherDescTextBox.Text;
        //    dl.aSWDvlpOther = aSWDvlpOtherCheckBox.Checked;
        //    dl.aSWDvlpHoardCollect = aSWDvlpHoardCollectCheckBox.Checked;
        //    dl.aSWDvlpCleanOrg = aSWDvlpCleanOrgCheckBox.Checked;
        //    dl.aSWDvlpEmoEat = aSWDvlpEmoEatCheckBox.Checked;
        //    dl.aSWDvlpShopping = aSWDvlpShoppingCheckBox.Checked;
        //    dl.aSWDvlpGambling = aSWDvlpGamblingCheckBox.Checked;
        //    dl.aSWDvlpNone = aSWDvlpNoneCheckBox.Checked;
        //    dl.aSWEffIneffTreatment = aSWEffIneffTreatmentTextBox.Text;
        //    dl.aSWHospPrevRemainComm = aSWHospPrevRemainCommTextBox.Text;
        //    dl.aSWHistHomSuicDesc = aSWHistHomSuicDescTextBox.Text;
        //    dl.aSWProbImpactFamDesc = aSWProbImpactFamDescTextBox.Text;
        //    dl.aSWOtherLegalDesc = aSWOtherLegalDescTextBox.Text;
        //    dl.aSWHistArrestDesc = aSWHistArrestDescTextBox.Text;
        //    dl.aSWHighestEduComplete = aSWHighestEduCompleteTextBox.Text;
        //    dl.aSWSchoolStressDesc = aSWSchoolStressDescTextBox.Text;
        //    dl.aSWCurrSchoolWhere = aSWCurrSchoolWhereTextBox.Text;
        //    dl.auditSubComplTotal = auditSubComplTotalTextBox.Text;
        //    dl.aSWSubAbuseResultNone = aSWSubAbuseResultNoneCheckBox.Checked;
        //    dl.aSWSubABuseResultOtherDesc = aSWSubAbuseResultOtherDescTextBox.Text;
        //    dl.aSWSubAbuseResultOther = aSWSubAbuseResultOtherCheckBox.Checked;
        //    dl.aSWSubAbuseResultPromis = aSWSubAbuseResultPromisCheckBox.Checked;
        //    dl.aSWSubAbuseResultWorkProb = aSWSubAbuseResultWorkProbCheckBox.Checked;
        //    dl.aSWSubAbuseResultBlackout = aSWSubAbuseResultBlackoutCheckBox.Checked;
        //    dl.aSWSubAbuseResultThoughtSelfHarm = aSWSubAbuseResultThoughtSelfHarmCheckBox.Checked;
        //    dl.aSWSubAbuseResultUnpBills = aSWSubAbuseResultUnpBillsCheckBox.Checked;
        //    dl.aSWSubAbuseResultRelatProb = aSWSubAbuseResultRelatProbCheckBox.Checked;
        //    dl.aSWSubAbuseResultArrest = aSWSubAbuseResultArrestCheckBox.Checked;
        //    dl.aSWSubAbuseNA = aSWSubAbuseNACheckBox.Checked;
        //    dl.aSWReferMadeDesc = aSWReferMadeDescTextBox.Text;
        //    dl.aSWReferMade = aSWReferMadeCheckBox.Checked;
        //    dl.aSWEduProvPat = aSWEduProvPatCheckBox.Checked;
        //    dl.aSWPatInformRecom = aSWPatInformRecomCheckBox.Checked;
        //    dl.aSWRecomDesc = aSWRecomDescTextBox.Text;
        //    dl.aSWRecom = aSWRecomCheckBox.Checked;
        //    dl.aSWInterventionOtherDesc = aSWInterventionOtherDescTextBox.Text;
        //    dl.aSWInterventionOther = aSWInterventionOtherCheckBox.Checked;
        //    dl.aSWAdvAbstain = aSWAdvAbstainCheckBox.Checked;
        //    dl.aSWMotDisc = aSWMotDiscCheckBox.Checked;
        //    dl.aSWDiscSeverity = aSWDiscSeverityCheckBox.Checked;
        //    dl.aSWDiscNegCons = aSWDiscNegConsCheckBox.Checked;
        //    dl.aSWFeedback = aSWFeedbackCheckBox.Checked;
        //    dl.aSWSubTreatHistDesc = aSWSubTreatHistDescTextBox.Text;
        //    dl.aSWSubTreatHist = aSWSubTreatHistCheckBox.Checked;
        //    dl.aSWBenefitUse = aSWBenefitUseTextBox.Text;
        //    dl.aSWDrugChoice = aSWDrugChoiceTextBox.Text;
        //    dl.aSWMilSigEvents = aSWMilSigEventsTextBox.Text;
        //    dl.aSWMilDischar = aSWMilDischarTextBox.Text;
        //    dl.aSWMilDates = aSWMilDatesTextBox.Text;
        //    dl.aSWMilBranch = aSWMilBranchTextBox.Text;
        //    dl.aSWSrcIncome = aSWSrcIncomeTextBox.Text;
        //    dl.aSWAvhMonIncome = aSWAvgMonIncomeTextBox.Text;
        //    dl.aSWFeelCurrWorkDesc = aSWFeelCurrWorkDescTextBox.Text;
        //    dl.aSWFeelCurrWork = aSWFeelCurrWorkCheckBox.Checked;
        //    dl.aSWWeNeedKnowDesc = aSWWeNeedKnowDescTextBox.Text;
        //    dl.aSWCultIssContribDesc = aSWCultIssContribDescTextBox.Text;
        //    dl.aSWCurrReligInvo = aSWCurrReligInvoTextBox.Text;
        //    dl.aSWChronDisabImpFunctDesc = aSWChronDisabImpFunctDescTextBox.Text;
        //    dl.aSWHistSigMedIssDesc = aSWHistSigMedIssDescTextBox.Text;
        //    dl.aSWMedIssContribDesc = aSWMedIssContribDescTextBox.Text;
        //    dl.aSWFinanceStressDesc = aSWFinanceStressDescTextBox.Text;
        //    dl.aSWObtMedNeedDesc = aSWObtMedNeedDescTextBox.Text;
        //    dl.aSWObtMedNeed = aSWObtMedNeedCheckBox.Checked;
        //    dl.aSWMedIncome = aSWObtMedIncomeCheckBox.Checked;
        //    dl.aSWMedTrans = aSWObtMedTransCheckBox.Checked;
        //    dl.aSWMAPartCommSuppResp = aSWMAPartCommSuppRespTextBox.Text;
        //    dl.aSWMAPartCommSuppWhen = aSWMAPartCommSuppWhenTextBox.Text;
        //    dl.aSWReadmOtherDesc = aSWReadmOtherDescTextBox.Text;
        //    dl.aSWReadmOther = aSWReadmOtherCheckBox.Checked;
        //    dl.aSWReadmCompli = aSWReadmCompliCheckBox.Checked;
        //    dl.aSWReadmPriorAuthor = aSWReadmPriorAuthorCheckBox.Checked;
        //    dl.aSWReadmMedStab = aSWReadmMedStabCheckBox.Checked;
        //    dl.aSWReadmNA = aSWReadmNACheckBox.Checked;
        //    dl.aSWCareNone = aSWCareNoneCheckBox.Checked;
        //    dl.aSWCareOtherDesc = aSWCareOtherDescTextBox.Text;
        //    dl.aSWCareOther = aSWCareOtherCheckBox.Checked;
        //    dl.aSWCareAcuteMed = aSWCareAcuteMedCheckBox.Checked;
        //    dl.aSWCareTrans = aSWCareTransCheckBox.Checked;
        //    dl.aSWCarePetsUnsup = aSWCarePetsUnsupCheckBox.Checked;
        //    dl.aSWCareHouse = aSWCareHouseCheckBox.Checked;
        //    dl.aSWCareHIstNonComp = aSWCareHIstNonCompCheckBox.Checked;
        //    dl.aSWArrSchedNeedDesc = aSWArrSchedNeedDescTextBox.Text;
        //    dl.aSWArrSchedNeed = aSWArrSchedNeedCheckBox.Checked;
        //    dl.aSWArrSchedMATP = aSWArrSchedMATPCheckBox.Checked;
        //    dl.aSWArrSchedFamFri = aSWArrSchedFamFriCheckBox.Checked;
        //    dl.aSWArrSchedPersVeh = aSWArrSchedPersVehCheckBox.Checked;
        //    dl.aSWPrelimDischargePlan = aSWPrelimDischargePlanTextBox.Text;
        //    dl.aSWRoleOtherDesc = aSWRoleOtherDescTextBox.Text;
        //    dl.aSWRoleOther = aSWRoleOtherCheckBox.Checked;
        //    dl.aSWRoleAftercare = aSWRoleAftercareCheckBox.Checked;
        //    dl.aSWRoleFamTher = aSWRoleFamTherCheckBox.Checked;
        //    dl.aSWRoleIndivTher = aSWRoleIndivTherCheckBox.Checked;
        //    dl.aSWRoleGrpTher = aSWRoleGrpTherCheckBox.Checked;
        //    dl.aSWConcRecom = aSWConcRecomTextBox.Text;
        //    dl.aSWReferNone = aSWReferNoneCheckBox.Checked;
        //    dl.aSWReferOtherDesc = aSWReferOtherDescTextBox.Text;
        //    dl.aSWReferOther = aSWReferOtherCheckBox.Checked;
        //    dl.aSWReferPeerSpec = aSWReferPeerSpecCheckBox.Checked;
        //    dl.aSWReferOutpatDA = aSWReferOutpatDACheckBox.Checked;
        //    dl.aSWReferPCPCheckBox = aSWReferPCPCheckBox.Checked;
        //    dl.aSWReferInpatDA = aSWReferInpatDACheckBox.Checked;
        //    dl.aSWReferCMBC = aSWReferCMBCMCheckBox.Checked;
        //    dl.aSWReferStateHosp = aSWReferStateHospCheckBox.Checked;
        //    dl.aSWReferEAC = aSWReferEACCheckBox.Checked;
        //    dl.aSWReferLTSRCRR = aSWReferLTSRCRRCheckBox.Checked;
        //    dl.aSWReferIOP = aSWReferIOPCheckBox.Checked;
        //    dl.aSWReferPsychRehab = aSWReferPsychRehabCheckBox.Checked;
        //    dl.aSWReferPHP = aSWReferPHPCheckBox.Checked;
        //    dl.aSWReferPsych = aSWReferPsychCheckBox.Checked;
        //    dl.aSWReferOutpat = aSWReferOutpatCheckBox.Checked;
        //    dl.aSWBarNone = aSWBarNoneCheckBox.Checked;
        //    dl.aSWBarOtherDesc = aSWBarOtherDescTextBox.Text;
        //    dl.aSWBarOther = aSWBarOtherCheckBox.Checked;
        //    dl.aSWBarAbsFacAccSpecNeed = aSWBarAbsFacAccSpecNeedCheckBox.Checked;
        //    dl.aSWBarNonComp = aSWBarNonCompCheckBox.Checked;
        //    dl.aSWBarHouse = aSWBarHouseCheckBox.Checked;
        //    dl.aSWBarMeds = aSWBarMedsCheckBox.Checked;
        //    dl.aSWBarTrans = aSWBarTransCheckBox.Checked;
        //    dl.aSWPrefPharm = aSWPrefPharmTextBox.Text;
        //}

        //private void getAdultSocialWork()
        //{
        //    aSWAssignWorkerTextBox.Text = dl.aSWAssignWorker;
        //    powAttorneyLNameTextBox.Text = dl.powAttorneyLName;
        //    powAttorneyFNameTextBox.Text = dl.powAttorneyFName;
        //    guardianshipLNameTextBox.Text = dl.guardianshipLName;
        //    guardianshipFNameTextBox.Text = dl.guardianshipFName;
        //    lastNameTextBox.Text = dl.lastName;
        //    firstNameTextBox.Text = dl.firstName;
        //    aSWDateCompleteDateTimePicker.Value = dl.aSWDateComplete;
        //    assessStartDateDateTimePicker.Value = dl.assessStartDate;
        //    aSWCommInvolveTextBox.Text = dl.aSWCommInvolve;
        //    aSWFamSupDescPatTextBox.Text = dl.aSWFamSupDesc;
        //    aSWPatDescSelfSomeoneTextBox.Text = dl.aSWPatDescSelfSomeone;
        //    aSWCurLevFuncDifTypFuncTextBox.Text = dl.aSWCurLevFuncDifTypFunc;
        //    aSWNaturePresProbTextBox.Text = dl.aSWNaturePresProb;
        //    aSWReliableSrcDescTextBox.Text = dl.aSWReliableSrcDesc;
        //    aSWSrcInfoTextBox.Text = dl.aSWSrcInfo;
        //    aSWLegStatDescTextBox.Text = dl.aSWLegStatDesc;
        //    aSWDangerSelfIntentCheckBox.Checked = dl.aSWDangerSelfIntent;
        //    aSWDangerSelfAttemptCheckBox.Checked = dl.aSWDangerSelfAttempt;
        //    aSWDangerSelfPlanCheckBox.Checked = dl.aSWDangerSelfPlan;
        //    aSWDangerSelfIdeationCheckBox.Checked = dl.aSWDangerSelfIdeation;
        //    aSWDangerSelfHistoryCheckBox.Checked = dl.aSWDangerSelfHistory;
        //    aSWDangerSelfCurrentCheckBox.Checked = dl.aSWDangerSelfCurrent;
        //    aSWDangerSelfNotPresCheckBox.Checked = dl.aSWDangerSelfNotPres;
        //    aSWWeaponLethMeansRemovePlanTextBox.Text = dl.aSWWeaponLethMeansRemovePlan;
        //    aSWPastSelfInjDescTextBox.Text = dl.aSWPastSelfInjDesc;
        //    aSWLethPriorMeansTextBox.Text = dl.aSWLethPriorMeans;
        //    aSWDangerDescTextBox.Text = dl.aSWDangerDesc;
        //    aSWDangerOthersNotPresCheckBox.Checked = dl.aSWDangerOthersNotPres;
        //    aSWDangerOthersIntentCheckBox.Checked = dl.aSWDangerOthersIntent;
        //    aSWDangerOthersAttemptCheckBox.Checked = dl.aSWDangerOthersAttempt;
        //    aSWDangerOthersPlanCheckBox.Checked = dl.aSWDangerOthersPlan;
        //    aSWDangerOthersIdeationCheckBox.Checked = dl.aSWDangerOthersIdeation;
        //    aSWDangerOthersHistoryCheckBox.Checked = dl.aSWDangerOthersHistory;
        //    aSWDangerOthersCurrentCheckBox.Checked = dl.aSWDangerOthersCurrent;
        //    aSWVerifyTimeTextBox.Text = dl.aSWVerifyTime;
        //    aSWVerifyDateDateTimePicker.Value = dl.aSWVerifyDate;
        //    aSWVerifyTextBox.Text = dl.aSWVerify;
        //    aSWResponsePatTimeTextBox.Text = dl.aSWResponsePatTime;
        //    aSWResponsePatDateDateTimePicker.Value = dl.aSWResponsePatDate;
        //    aSWResponsePatTextBox.Text = dl.aSWResponsePat;
        //    aSWEmoNegAbuseReportedDescTextBox.Text = dl.aSWEmoNegAbuseReportedDesc;
        //    aSWEmoNegAbuseWitnessDescTextBox.Text = dl.aSWEmoNegAbuseWitnessDesc;
        //    aSWPhsyAbuseReportDescTextBox.Text = dl.aSWPhsyAbuseReportDesc;
        //    aSWPhsyAbuseWitnessDescTextBox.Text = dl.aSWPhsyAbuseWitnessDesc;
        //    aSWSexAbuseReportDescTextBox.Text = dl.aSWSexAbuseReportDesc;
        //    aSWSexAbuseWitnessDescTextBox.Text = dl.aSWSexAbuseWitnessDesc;
        //    aSWOtherTraumaExpTextBox.Text = dl.aSWOtherTraumaExp;
        //    aSWTermPregDescTextBox.Text = dl.aSWTermPregDesc;
        //    aSWDateChangeDateTimePicker.Value = dl.aSWDateChange;
        //    aSWSafeHomeDescTextBox.Text = dl.aSWSafeHomeDesc;
        //    aSWHomePlanDischTextBox.Text = dl.aSWHomePlanDisch;
        //    aSWRetHomeWhenTextBox.Text = dl.aSWRetHomeWhen;
        //    aSWRetHomeWhomTextBox.Text = dl.aSWRetHomeWhom;
        //    aSWHomePriorTextBox.Text = dl.aSWHomePrior;
        //    aSWRecFamInvolveTextBox.Text = dl.aSWRecFamInvolve;
        //    aSWFamDeclineReasonTextBox.Text = dl.aSWFamDeclineReason;
        //    aSWFamSessInviteTextBox.Text = dl.aSWFamSessInvite;
        //    aSWDateFamSessDateTimePicker.Value = dl.aSWDateFamSess;
        //    aSWRelatProbTextBox.Text = dl.aSWRelatProb;
        //    aSWMemHelpfulDescTextBox.Text = dl.aSWMemHelpfulDesc;
        //    aSWPriorFamInvolveTextBox.Text = dl.aSWPriorFamInvolve;
        //    aSWDvlpExplainTextBox.Text = dl.aSWDvlpExplain;
        //    aSWDvlpOtherDescTextBox.Text = dl.aSWDvlpOtherDesc;
        //    aSWDvlpOtherCheckBox.Checked = dl.aSWDvlpOther;
        //    aSWDvlpHoardCollectCheckBox.Checked = dl.aSWDvlpHoardCollect;
        //    aSWDvlpCleanOrgCheckBox.Checked = dl.aSWDvlpCleanOrg;
        //    aSWDvlpEmoEatCheckBox.Checked = dl.aSWDvlpEmoEat;
        //    aSWDvlpShoppingCheckBox.Checked = dl.aSWDvlpShopping;
        //    aSWDvlpGamblingCheckBox.Checked = dl.aSWDvlpGambling;
        //    aSWDvlpNoneCheckBox.Checked = dl.aSWDvlpNone;
        //    aSWEffIneffTreatmentTextBox.Text = dl.aSWEffIneffTreatment;
        //    aSWHospPrevRemainCommTextBox.Text = dl.aSWHospPrevRemainComm;
        //    aSWHistHomSuicDescTextBox.Text = dl.aSWHistHomSuicDesc;
        //    aSWProbImpactFamDescTextBox.Text = dl.aSWProbImpactFamDesc;
        //    aSWOtherLegalDescTextBox.Text = dl.aSWOtherLegalDesc;
        //    aSWHistArrestDescTextBox.Text = dl.aSWHistArrestDesc;
        //    aSWHighestEduCompleteTextBox.Text = dl.aSWHighestEduComplete;
        //    aSWSchoolStressDescTextBox.Text = dl.aSWSchoolStressDesc;
        //    aSWCurrSchoolWhereTextBox.Text = dl.aSWCurrSchoolWhere;
        //    auditSubComplTotalTextBox.Text = dl.auditSubComplTotal;
        //    aSWSubAbuseResultNoneCheckBox.Checked = dl.aSWSubAbuseResultNone;
        //    aSWSubAbuseResultOtherDescTextBox.Text = dl.aSWSubABuseResultOtherDesc;
        //    aSWSubAbuseResultOtherCheckBox.Checked = dl.aSWSubAbuseResultOther;
        //    aSWSubAbuseResultPromisCheckBox.Checked = dl.aSWSubAbuseResultPromis;
        //    aSWSubAbuseResultWorkProbCheckBox.Checked = dl.aSWSubAbuseResultWorkProb;
        //    aSWSubAbuseResultBlackoutCheckBox.Checked = dl.aSWSubAbuseResultBlackout;
        //    aSWSubAbuseResultThoughtSelfHarmCheckBox.Checked = dl.aSWSubAbuseResultThoughtSelfHarm;
        //    aSWSubAbuseResultUnpBillsCheckBox.Checked = dl.aSWSubAbuseResultUnpBills;
        //    aSWSubAbuseResultRelatProbCheckBox.Checked = dl.aSWSubAbuseResultRelatProb;
        //    aSWSubAbuseResultArrestCheckBox.Checked = dl.aSWSubAbuseResultArrest;
        //    aSWSubAbuseNACheckBox.Checked = dl.aSWSubAbuseNA;
        //    aSWReferMadeDescTextBox.Text = dl.aSWReferMadeDesc;
        //    aSWReferMadeCheckBox.Checked = dl.aSWReferMade;
        //    aSWEduProvPatCheckBox.Checked = dl.aSWEduProvPat;
        //    aSWPatInformRecomCheckBox.Checked = dl.aSWPatInformRecom;
        //    aSWRecomDescTextBox.Text = dl.aSWRecomDesc;
        //    aSWRecomCheckBox.Checked = dl.aSWRecom;
        //    aSWInterventionOtherDescTextBox.Text = dl.aSWInterventionOtherDesc;
        //    aSWInterventionOtherCheckBox.Checked = dl.aSWInterventionOther;
        //    aSWAdvAbstainCheckBox.Checked = dl.aSWAdvAbstain;
        //    aSWMotDiscCheckBox.Checked = dl.aSWMotDisc;
        //    aSWDiscSeverityCheckBox.Checked = dl.aSWDiscSeverity;
        //    aSWDiscNegConsCheckBox.Checked = dl.aSWDiscNegCons;
        //    aSWFeedbackCheckBox.Checked = dl.aSWFeedback;
        //    aSWSubTreatHistDescTextBox.Text = dl.aSWSubTreatHistDesc;
        //    aSWSubTreatHistCheckBox.Checked = dl.aSWSubTreatHist;
        //    aSWBenefitUseTextBox.Text = dl.aSWBenefitUse;
        //    aSWDrugChoiceTextBox.Text = dl.aSWDrugChoice;
        //    aSWMilSigEventsTextBox.Text = dl.aSWMilSigEvents;
        //    aSWMilDischarTextBox.Text = dl.aSWMilDischar;
        //    aSWMilDatesTextBox.Text = dl.aSWMilDates;
        //    aSWMilBranchTextBox.Text = dl.aSWMilBranch;
        //    aSWSrcIncomeTextBox.Text = dl.aSWSrcIncome;
        //    aSWAvgMonIncomeTextBox.Text = dl.aSWAvhMonIncome;
        //    aSWFeelCurrWorkDescTextBox.Text = dl.aSWFeelCurrWorkDesc;
        //    aSWFeelCurrWorkCheckBox.Checked = dl.aSWFeelCurrWork;
        //    aSWWeNeedKnowDescTextBox.Text = dl.aSWWeNeedKnowDesc;
        //    aSWCultIssContribDescTextBox.Text = dl.aSWCultIssContribDesc;
        //    aSWCurrReligInvoTextBox.Text = dl.aSWCurrReligInvo;
        //    aSWChronDisabImpFunctDescTextBox.Text = dl.aSWChronDisabImpFunctDesc;
        //    aSWHistSigMedIssDescTextBox.Text = dl.aSWHistSigMedIssDesc;
        //    aSWMedIssContribDescTextBox.Text = dl.aSWMedIssContribDesc;
        //    aSWFinanceStressDescTextBox.Text = dl.aSWFinanceStressDesc;
        //    aSWObtMedNeedDescTextBox.Text = dl.aSWObtMedNeedDesc;
        //    aSWObtMedNeedCheckBox.Checked = dl.aSWObtMedNeed;
        //    aSWObtMedIncomeCheckBox.Checked = dl.aSWMedIncome;
        //    aSWObtMedTransCheckBox.Checked = dl.aSWMedTrans;
        //    aSWMAPartCommSuppRespTextBox.Text = dl.aSWMAPartCommSuppResp;
        //    aSWMAPartCommSuppWhenTextBox.Text = dl.aSWMAPartCommSuppWhen;
        //    aSWReadmOtherDescTextBox.Text = dl.aSWReadmOtherDesc;
        //    aSWReadmOtherCheckBox.Checked = dl.aSWReadmOther;
        //    aSWReadmCompliCheckBox.Checked = dl.aSWReadmCompli;
        //    aSWReadmPriorAuthorCheckBox.Checked = dl.aSWReadmPriorAuthor;
        //    aSWReadmMedStabCheckBox.Checked = dl.aSWReadmMedStab;
        //    aSWReadmNACheckBox.Checked = dl.aSWReadmNA;
        //    aSWCareNoneCheckBox.Checked = dl.aSWCareNone;
        //    aSWCareOtherDescTextBox.Text = dl.aSWCareOtherDesc;
        //    aSWCareOtherCheckBox.Checked = dl.aSWCareOther;
        //    aSWCareAcuteMedCheckBox.Checked = dl.aSWCareAcuteMed;
        //    aSWCareTransCheckBox.Checked = dl.aSWCareTrans;
        //    aSWCarePetsUnsupCheckBox.Checked = dl.aSWCarePetsUnsup;
        //    aSWCareHouseCheckBox.Checked = dl.aSWCareHouse;
        //    aSWCareHIstNonCompCheckBox.Checked = dl.aSWCareHIstNonComp;
        //    aSWArrSchedNeedDescTextBox.Text = dl.aSWArrSchedNeedDesc;
        //    aSWArrSchedNeedCheckBox.Checked = dl.aSWArrSchedNeed;
        //    aSWArrSchedMATPCheckBox.Checked = dl.aSWArrSchedMATP;
        //    aSWArrSchedFamFriCheckBox.Checked = dl.aSWArrSchedFamFri;
        //    aSWArrSchedPersVehCheckBox.Checked = dl.aSWArrSchedPersVeh;
        //    aSWPrelimDischargePlanTextBox.Text = dl.aSWPrelimDischargePlan;
        //    aSWRoleOtherDescTextBox.Text = dl.aSWRoleOtherDesc;
        //    aSWRoleOtherCheckBox.Checked = dl.aSWRoleOther;
        //    aSWRoleAftercareCheckBox.Checked = dl.aSWRoleAftercare;
        //    aSWRoleFamTherCheckBox.Checked = dl.aSWRoleFamTher;
        //    aSWRoleIndivTherCheckBox.Checked = dl.aSWRoleIndivTher;
        //    aSWRoleGrpTherCheckBox.Checked = dl.aSWRoleGrpTher;
        //    aSWConcRecomTextBox.Text = dl.aSWConcRecom;
        //    aSWReferNoneCheckBox.Checked = dl.aSWReferNone;
        //    aSWReferOtherDescTextBox.Text = dl.aSWReferOtherDesc;
        //    aSWReferOtherCheckBox.Checked = dl.aSWReferOther;
        //    aSWReferPeerSpecCheckBox.Checked = dl.aSWReferPeerSpec;
        //    aSWReferOutpatDACheckBox.Checked = dl.aSWReferOutpatDA;
        //    aSWReferPCPCheckBox.Checked = dl.aSWReferPCPCheckBox;
        //    aSWReferInpatDACheckBox.Checked = dl.aSWReferInpatDA;
        //    aSWReferCMBCMCheckBox.Checked = dl.aSWReferCMBC;
        //    aSWReferStateHospCheckBox.Checked = dl.aSWReferStateHosp;
        //    aSWReferEACCheckBox.Checked = dl.aSWReferEAC;
        //    aSWReferLTSRCRRCheckBox.Checked = dl.aSWReferLTSRCRR;
        //    aSWReferIOPCheckBox.Checked = dl.aSWReferIOP;
        //    aSWReferPsychRehabCheckBox.Checked = dl.aSWReferPsychRehab;
        //    aSWReferPHPCheckBox.Checked = dl.aSWReferPHP;
        //    aSWReferPsychCheckBox.Checked = dl.aSWReferPsych;
        //    aSWReferOutpatCheckBox.Checked = dl.aSWReferOutpat;
        //    aSWBarNoneCheckBox.Checked = dl.aSWBarNone;
        //    aSWBarOtherDescTextBox.Text = dl.aSWBarOtherDesc;
        //    aSWBarOtherCheckBox.Checked = dl.aSWBarOther;
        //    aSWBarAbsFacAccSpecNeedCheckBox.Checked = dl.aSWBarAbsFacAccSpecNeed;
        //    aSWBarNonCompCheckBox.Checked = dl.aSWBarNonComp;
        //    aSWBarHouseCheckBox.Checked = dl.aSWBarHouse;
        //    aSWBarMedsCheckBox.Checked = dl.aSWBarMeds;
        //    aSWBarTransCheckBox.Checked = dl.aSWBarTrans;
        //    aSWPrefPharmTextBox.Text = dl.aSWPrefPharm;
        //}

        private void grpRiskAssess_Enter(object sender, EventArgs e)
        {

        }
    }
}
