//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class allergy
    {
        public int PatientID { get; set; }
        public string AllergicType { get; set; }
        public string AllergicTypeDesc { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
