//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CPCAppEntities : DbContext
    {
        public CPCAppEntities()
            : base("name=CPCAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abuse_assessment> abuse_assessment { get; set; }
        public virtual DbSet<allergy> allergies { get; set; }
        public virtual DbSet<deffered_problem_list> deffered_problem_list { get; set; }
        public virtual DbSet<family_members> family_members { get; set; }
        public virtual DbSet<function> functions { get; set; }
        public virtual DbSet<intervention> interventions { get; set; }
        public virtual DbSet<medical_problem_list> medical_problem_list { get; set; }
        public virtual DbSet<medication> medications { get; set; }
        public virtual DbSet<pain_assessment> pain_assessment { get; set; }
        public virtual DbSet<patient_admission> patient_admission { get; set; }
        public virtual DbSet<patient_admission_ext> patient_admission_ext { get; set; }
        public virtual DbSet<precaution> precautions { get; set; }
        public virtual DbSet<psych_hospital> psych_hospital { get; set; }
        public virtual DbSet<psychiatric_problem_list> psychiatric_problem_list { get; set; }
        public virtual DbSet<short_term_goals> short_term_goals { get; set; }
        public virtual DbSet<substance_abuse> substance_abuse { get; set; }
        public virtual DbSet<treatment_facility> treatment_facility { get; set; }
    }
}
