using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExampleLook
{
    public class DataLayer
    {
        public DataLayer()
        {
        }

        public string inactive { get; set; }
        public int patientID { get; set; }
        public string currentPatient { get; set; }
        public string callerFName { get; set; }
        public string callerLName { get; set; }
        public string callerCity { get; set; }
        public string callerState { get; set; }
        public string callerZip { get; set; }
        public string callerPhone { get; set; }
        public string callerRefName { get; set; }
        public string callerAgency { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string lastName { get; set; }
        public string prefLang { get; set; }
        public string prefLangDesc { get; set; }
        public string age { get; set; }
        public Nullable<System.DateTime> dOB { get; set; }
        public string gender { get; set; }
        public string sSN { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string county { get; set; }
        public string phone { get; set; }
        public string genderID { get; set; }
        public string commitStat { get; set; }
        public string commitStatDesc { get; set; }
        public string presentProb { get; set; }
        public string presentSuicide { get; set; }
        public string presentSelfHarm { get; set; }
        public string presentHomicide { get; set; }
        public string presentPsychosis { get; set; }
        public string presentOther { get; set; }
        public string presentOtherDesc { get; set; }
        public string lethalMeans { get; set; }
        public string subMisuse { get; set; }
        public string prevTx { get; set; }
        public string currentOutpat { get; set; }
        public string medConcerns { get; set; }
        public string potentialPreg { get; set; }
        public string intelDisable { get; set; }
        public Nullable<int> iQ { get; set; }
        public string sexVictim { get; set; }
        public string sexVictimDesc { get; set; }
        public string sexAggress { get; set; }
        public string sexAggressDesc { get; set; }
        public string allergies { get; set; }
        public string bloodPressure { get; set; }
        public string t { get; set; }
        public string p { get; set; }
        public string r { get; set; }
        public string vitalsNotObtain { get; set; }
        public string stableTrans { get; set; }
        public string nurseIntake { get; set; }
        public string milStat { get; set; }
        public string primInsName { get; set; }
        public string primInsPhone { get; set; }
        public string secInsName { get; set; }
        public string secInsPhone { get; set; }
        public string medEduRights { get; set; }
        public string medEduRightsFName { get; set; }
        public string medEduRightsLName { get; set; }
        public string medEduRightsRelat { get; set; }
        public string medEduRightsPhone { get; set; }
        public string guardianship { get; set; }
        public string guardianshipFName { get; set; }
        public string guardianshipLName { get; set; }
        public string guardianshipRelat { get; set; }
        public string guardianshipPhone { get; set; }
        public string powAttorney { get; set; }
        public string powAttorneyFName { get; set; }
        public string powAttorneyLName { get; set; }
        public string powAttorneyRelat { get; set; }
        public string powAttorneyPhone { get; set; }
        public string emergencyContact { get; set; }
        public string emergencyContactFName { get; set; }
        public string emergencyContactLName { get; set; }
        public string emergencyContactRelat { get; set; }
        public string emergencyContactPhone { get; set; }
        public string schedAssess { get; set; }
        public Nullable<System.DateTime> schedAssessDate { get; set; }
        public string schedAssessTime { get; set; }
        public string faxLab { get; set; }
        public string physOnCall { get; set; }
        public string nurseNotified { get; set; }
        public string timeAcceptedNA { get; set; }
        public Nullable<System.DateTime> timeAccepted { get; set; }
        public string admPsyDiag { get; set; }
        public string medDiag { get; set; }
        public string transport { get; set; }
        public string transportDesc { get; set; }
        public string callNotes { get; set; }
        public string callCollectedBy { get; set; }
        public string callEndedTime { get; set; }
        public Nullable<System.DateTime> callEnded { get; set; }
        public string callStartedTime { get; set; }
        public Nullable<System.DateTime> callStarted { get; set; }
        public string mRNum { get; set; }
        public string maritalStat { get; set; }
        public string race { get; set; }
        public Nullable<System.DateTime> assessStartDate { get; set; }
        public string assessStartTime { get; set; }
        public string srcInfo { get; set; }
        public string chiefComplaint { get; set; }
        public string moodApp { get; set; }
        public string moodDep { get; set; }
        public string moodLab { get; set; }
        public string moodAnx { get; set; }
        public string moodIrr { get; set; }
        public string moodEup { get; set; }
        public string moodHos { get; set; }
        public string moodOther { get; set; }
        public string moodOtherVal { get; set; }
        public string thoughtProcLog { get; set; }
        public string thoughtProcCon { get; set; }
        public string thoughtProcTan { get; set; }
        public string thoughtProcLoo { get; set; }
        public string thoughtProcRac { get; set; }
        public string thoughtProcObs { get; set; }
        public string thoughtProcBlo { get; set; }
        public string thoughtProcDis { get; set; }
        public string thoughtContRea { get; set; }
        public string thoughtContPre { get; set; }
        public string thoughtContGra { get; set; }
        public string thoughtContPar { get; set; }
        public string thoughtContDel { get; set; }
        public string thoughtContSom { get; set; }
        public string thoughtContHal { get; set; }
        public string thoughtContHalType { get; set; }
        public string affApp { get; set; }
        public string affIna { get; set; }
        public string affBlu { get; set; }
        public string affRes { get; set; }
        public string affLab { get; set; }
        public string affTear { get; set; }
        public string affCon { get; set; }
        public string affIncon { get; set; }
        public string insight { get; set; }
        public string judgement { get; set; }
        public string speechApp { get; set; }
        public string speechPre { get; set; }
        public string speechRam { get; set; }
        public string speechLoud { get; set; }
        public string speechHos { get; set; }
        public string speechMon { get; set; }
        public string speechOther { get; set; }
        public string speechOtherVal { get; set; }
        public string orientPer { get; set; }
        public string orientPla { get; set; }
        public string orientTim { get; set; }
        public string orientSit { get; set; }
        public string orientDis { get; set; }
        public string appearance { get; set; }
        public string motorBehavior { get; set; }
        public string motorBehaviorDesc { get; set; }
        public string appeApp { get; set; }
        public string appeDec { get; set; }
        public string appeInc { get; set; }
        public string appeGai { get; set; }
        public string appeGaiValue { get; set; }
        public string appeLos { get; set; }
        public string appeLosValue { get; set; }
        public string appeUna { get; set; }
        public string sleApp { get; set; }
        public string sleDec { get; set; }
        public string sleDecValue { get; set; }
        public string sleInc { get; set; }
        public string sleIncValue { get; set; }
        public string sleDif { get; set; }
        public string sleInt { get; set; }
        public string sleNig { get; set; }
        public string sleUna { get; set; }
        public string idData { get; set; }
        public string medHistory { get; set; }
        public string surgical { get; set; }
        public string histMRSA { get; set; }
        public string histMRSAExpl { get; set; }
        public string dietRest { get; set; }
        public string dietRestExpl { get; set; }
        public string histFalls { get; set; }
        public string histFallsExpl { get; set; }
        public string pCP { get; set; }
        public string pCPName { get; set; }
        public string outMentHealth { get; set; }
        public string complTreat { get; set; }
        public string complTreatBarr { get; set; }
        public string psychHosp { get; set; }
        public string histNonCompMed { get; set; }
        public string reHospNonComp { get; set; }
        public string prevDiag { get; set; }
        public string prevDiagExpl { get; set; }
        public string autismSpecDis { get; set; }
        public string deniesLegal { get; set; }
        public string currentLegal { get; set; }
        public string probation { get; set; }
        public string parole { get; set; }
        public string legalCounty { get; set; }
        public string charges { get; set; }
        public string incarc { get; set; }
        public string incarcExpl { get; set; }
        public string deniesSuic { get; set; }
        public string suicIdeaYes { get; set; }
        public string suicIdeaNoPlan { get; set; }
        public string suicIdeaMethod { get; set; }
        public string suicIdeaPlan { get; set; }
        public string suicIdeaIntent { get; set; }
        public string suicIdeaMeans { get; set; }
        public string suicIdeaDesc { get; set; }
        public string violSelf6Mo { get; set; }
        public string violSelf6MoDesc { get; set; }
        public string suicPriorAtt { get; set; }
        public string suicPriorAttDesc { get; set; }
        public string famHistSuic { get; set; }
        public string famHistSuicDesc { get; set; }
        public string attemptInpat { get; set; }
        public string attemptInpatDesc { get; set; }
        public string assoHopeless { get; set; }
        public string assoHelpless { get; set; }
        public string assoSad { get; set; }
        public string assoTearful { get; set; }
        public string assoImpulsive { get; set; }
        public string assoIsolative { get; set; }
        public string suicAttInpatient { get; set; }
        public string suicAttInpatientDesc { get; set; }
        public string DeniesSelfInj { get; set; }
        public string selfInjLastAtt { get; set; }
        public string selfInjInpatient { get; set; }
        public string selfInjInpatientDesc { get; set; }
        public string DeniesHom { get; set; }
        public string homIdeaYes { get; set; }
        public string homIdeaPlan { get; set; }
        public string homIdeaNoPlan { get; set; }
        public string homIdeaIntent { get; set; }
        public string homIdeaMeans { get; set; }
        public string homIdeaDesc { get; set; }
        public string homIdeaTarget { get; set; }
        public string violOthers6Mo { get; set; }
        public string violOthers6MoDesc { get; set; }
        public string violOtherHist { get; set; }
        public string violOtherHistDesc { get; set; }
        public string homPriorAtt { get; set; }
        public string homPriorAttDesc { get; set; }
        public string famHistHom { get; set; }
        public string famHistHomDesc { get; set; }
        public string accessWeap { get; set; }
        public string accessWeapDesc { get; set; }
        public string DeniesAssa { get; set; }
        public string histAssaBeh { get; set; }
        public string hisAssaBehDesc { get; set; }
        public string angerProb { get; set; }
        public string angerProbDesc { get; set; }
        public string DeniesPsychFam { get; set; }
        public string psychFam { get; set; }
        public string psychFamDesc { get; set; }
        public string DeniesHistAbuse { get; set; }
        public string traumEve { get; set; }
        public string traumEveDesc { get; set; }
        public string combVic { get; set; }
        public string combVicDesc { get; set; }
        public string incProm { get; set; }
        public string incPromDesc { get; set; }
        public string expSelf { get; set; }
        public string expSelfDesc { get; set; }
        public string megLaw { get; set; }
        public string sexAggRiskBeh { get; set; }
        public string histSexAggBeh { get; set; }
        public string sexPreocc { get; set; }
        public string histCrimSex { get; set; }
        public string psychSexPreocc { get; set; }
        public string secVicRisk { get; set; }
        public string DevDelay { get; set; }
        public string vicSexPreocc { get; set; }
        public string phyStatus { get; set; }
        public string vicSexAbuse { get; set; }
        public string medComp { get; set; }
        public string DeniesMisuse { get; set; }
        public string deniesAlcDrugTreat { get; set; }
        public string currentAlcDrugTreat { get; set; }
        public string currentAlcDrugTreatDesc { get; set; }
        public string alcDrugHist { get; set; }
        public string alcDrugHistDesc { get; set; }
        public string histWithdrawSymp { get; set; }
        public string histWIthdrawSympDesc { get; set; }
        public string delTrem { get; set; }
        public string longPerSober { get; set; }
        public string longPerSoberDesc { get; set; }
        public string subLegalProb { get; set; }
        public string subLegalProbDesc { get; set; }
        public string famHistSubAbu { get; set; }
        public string famHistSubAbuDesc { get; set; }
        public string currentTobUse { get; set; }
        public string currentTobUseDesc { get; set; }
        public string howOftenAlc { get; set; }
        public string howManyAlcTyp { get; set; }
        public string howOftenSix { get; set; }
        public string auditSubComplTotal { get; set; }
        public string deniesPsychosis { get; set; }
        public string psychHall { get; set; }
        public string psychHallDesc { get; set; }
        public string psychComm { get; set; }
        public string psychCommDesc { get; set; }
        public string psychDel { get; set; }
        public string psychDelDesc { get; set; }
        public string psychRel { get; set; }
        public string psychRelDesc { get; set; }
        public string highLevEdu { get; set; }
        public string employed { get; set; }
        public string employedDesc { get; set; }
        public string repPayee { get; set; }
        public string repPayeeDesc { get; set; }
        public string disability { get; set; }
        public string disabilityDesc { get; set; }
        public string siblings { get; set; }
        public string siblingsDesc { get; set; }
        public string children { get; set; }
        public string childrenDesc { get; set; }
        public string childUnd18Care { get; set; }
        public string livingSituation { get; set; }
        public string livingSituationDesc { get; set; }
        public string supports { get; set; }
        public string strCopSkills { get; set; }
        public string medCompliant { get; set; }
        public string medCompliantDesc { get; set; }
        public string medNotes { get; set; }
        public string education { get; set; }
        public string curSchoolNam { get; set; }
        public string encoEnur { get; set; }
        public string encoEnurDesc { get; set; }
        public string cruelAnimals { get; set; }
        public string cruelAnimalsDesc { get; set; }
        public string fireSet { get; set; }
        public string fireSetDesc { get; set; }
        public string stealing { get; set; }
        public string stealingDesc { get; set; }
        public string lying { get; set; }
        public string lyingDesc { get; set; }
        public string runAway { get; set; }
        public string runAwayDesc { get; set; }
        public string rebel { get; set; }
        public string rebelHome { get; set; }
        public string rebelSchool { get; set; }
        public string rebelDesc { get; set; }
        public string detSchPer { get; set; }
        public string detSchPerDesc { get; set; }
        public string probSchool { get; set; }
        public string probSchoolDesc { get; set; }
        public string indivEduProg { get; set; }
        public string indivEduProgLearnSup { get; set; }
        public string indivEduProgEmoSup { get; set; }
        public string difMakeFriends { get; set; }
        public string difMakeFriendsDesc { get; set; }
        public string schRefu { get; set; }
        public string schRefuDesc { get; set; }
        public string bullied { get; set; }
        public string bulliedDesc { get; set; }
        public string bullyOth { get; set; }
        public string bullyOthDesc { get; set; }
        public string depSympSad { get; set; }
        public string depSympCrying { get; set; }
        public string depSympHopeless { get; set; }
        public string depSympHelpless { get; set; }
        public string depSympWithdrawn { get; set; }
        public string depSympIsolative { get; set; }
        public string depSympIrritable { get; set; }
        public string moodLabSwings { get; set; }
        public string moodLabAggBeh { get; set; }
        public string moodLabEsc { get; set; }
        public string moodLabGrand { get; set; }
        public string moodLabPoor { get; set; }
        public string anxRelPhys { get; set; }
        public string anxRelHand { get; set; }
        public string anxRelOCDTho { get; set; }
        public string anxRelOCDBeh { get; set; }
        public string physContact { get; set; }
        public Nullable<System.DateTime> timeReviewed { get; set; }
        public string physRecAdmit { get; set; }
        public string physRecRefer { get; set; }a
        public string physRecDesc { get; set; }
        public string attPhys { get; set; }
        public string staffCompIntake { get; set; }
        public Nullable<System.DateTime> staffCompIntakeDateTime { get; set; }
        public string staffPrepIntakeDoc { get; set; }
        public Nullable<System.DateTime> staffPrepIntakeDocDateTime { get; set; }
        public string metalDetect { get; set; }
        public string metalDetectExpl { get; set; }
        public string provDiagInpatient { get; set; }
        public string provDiagPartHosp { get; set; }
        public string provDiagNA { get; set; }
        public string medDiagNone { get; set; }
        public string psychosocialFact { get; set; }
        public string psychosocialFactDesc { get; set; }
        public string contextFact { get; set; }
        public string contextFactDesc { get; set; }
        public string funcAssess { get; set; }
        public Nullable<System.DateTime> physicianDateTime { get; set; }
        public string fifteenMinChecks { get; set; }
        public string oneToOneChecks { get; set; }
        public string unitRestriction { get; set; }
        public string gymRestriction { get; set; }
        public string precautionSuicide { get; set; }
        public string precautionSexAgg { get; set; }
        public string precautionSexVic { get; set; }
        public string precautionAssault { get; set; }
        public string precautionElope { get; set; }
        public string precautionMedRisk { get; set; }
        public string precautionFall { get; set; }
        public string precautionSelfHarm { get; set; }
        public string precautionNone { get; set; }
        public string arcStaffName { get; set; }
        public string unitStaffName { get; set; }
        public string hairColor { get; set; }
        public string eyeColor { get; set; }
        public string height { get; set; }
        public string heighCm { get; set; }
        public string weight { get; set; }
        public string weightKg { get; set; }
        public string waist { get; set; }
        public string waistCm { get; set; }
        public string currentReportPain { get; set; }
        public string yesFullAssess { get; set; }
        public string noSkipPain { get; set; }
        public string applyHeat { get; set; }
        public string applyCold { get; set; }
        public string resting { get; set; }
        public string elevation { get; set; }
        public string deepBreathing { get; set; }
        public string relaxation { get; set; }
        public string medication { get; set; }
        public string medicationDesc { get; set; }
        public string painOther { get; set; }
        public string painOtherDesc { get; set; }
        public string sexualActive { get; set; }
        public string denySex { get; set; }
        public string prefMale { get; set; }
        public string prefFemale { get; set; }
        public string prefBi { get; set; }
        public string prefPan { get; set; }
        public string prefOther { get; set; }
        public string prefOtherDesc { get; set; }
        public string sTDHist { get; set; }
        public string sTDHistDesc { get; set; }
        public string denyCardio { get; set; }
        public string chestPain { get; set; }
        public string pacemaker { get; set; }
        public string mI { get; set; }
        public string pVD { get; set; }
        public string palitations { get; set; }
        public string irregPulse { get; set; }
        public string hypertension { get; set; }
        public string hypotension { get; set; }
        public string edema { get; set; }
        public string arrhythmia { get; set; }
        public string heartFailure { get; set; }
        public string cardioOther { get; set; }
        public string cardioOtherDesc { get; set; }
        public string gastroDeny { get; set; }
        public string nausea { get; set; }
        public string gastroPain { get; set; }
        public string gERD { get; set; }
        public string gastroUlcers { get; set; }
        public string hernia { get; set; }
        public string livDisease { get; set; }
        public string gastroOther { get; set; }
        public string gastroOtherDesc { get; set; }
        public string bowelDeny { get; set; }
        public string diarrhea { get; set; }
        public string constipation { get; set; }
        public string hemmoroids { get; set; }
        public string incont { get; set; }
        public string lax { get; set; }
        public string antiDiarrheal { get; set; }
        public string bowelOther { get; set; }
        public string bowelOtherDesc { get; set; }
        public string lastBM { get; set; }
        public string dentalDeny { get; set; }
        public string denturesUp { get; set; }
        public string denturesLow { get; set; }
        public string denturesPart { get; set; }
        public string looseMissingTeeth { get; set; }
        public string dentalUlcers { get; set; }
        public string bleedingGums { get; set; }
        public string extractions { get; set; }
        public string dentalOther { get; set; }
        public string dentalOtherDesc { get; set; }
        public string noseThroatDeny { get; set; }
        public string sinus { get; set; }
        public string soreThroat { get; set; }
        public string hoarseness { get; set; }
        public string diffSwallow { get; set; }
        public string coldSympt { get; set; }
        public string thrush { get; set; }
        public string noseThroatOther { get; set; }
        public string noseThroatOtherDesc { get; set; }
        public string respDeny { get; set; }
        public string shortBreath { get; set; }
        public string laboredBreath { get; set; }
        public string asthma { get; set; }
        public string cough { get; set; }
        public string cOPD { get; set; }
        public string sleepApnea { get; set; }
        public string cPAP { get; set; }
        public string respOther { get; set; }
        public string respOtherDesc { get; set; }
        public string neuroDeny { get; set; }
        public string seizures { get; set; }
        public string lastSeizure { get; set; }
        public string stroke { get; set; }
        public string freqHeadache { get; set; }
        public string neuroConfusion { get; set; }
        public string weakParalysis { get; set; }
        public string headInjuryTrauma { get; set; }
        public string dizziness { get; set; }
        public string tremors { get; set; }
        public string migraine { get; set; }
        public string neuroOther { get; set; }
        public string neuroOtherDesc { get; set; }
        public string skinDeny { get; set; }
        public string skinUlcers { get; set; }
        public string scars { get; set; }
        public string bruises { get; set; }
        public string rashHives { get; set; }
        public string discolor { get; set; }
        public string itching { get; set; }
        public string wound { get; set; }
        public string sutures { get; set; }
        public string numSutures { get; set; }
        public string staples { get; set; }
        public string staplesNum { get; set; }
        public string skinOther { get; set; }
        public string skinOtherDesc { get; set; }
        public string genitDeny { get; set; }
        public string burning { get; set; }
        public string nocturia { get; set; }
        public string hematuria { get; set; }
        public string uTI { get; set; }
        public string genitFreqInc { get; set; }
        public string genitFreqDec { get; set; }
        public string hesitancy { get; set; }
        public string incontinence { get; set; }
        public string genitOther { get; set; }
        public string genitOtherDesc { get; set; }
        public string endoDeny { get; set; }
        public string endoDiabetes { get; set; }
        public string endoInsulin { get; set; }
        public string dietControlled { get; set; }
        public string diagEndoDis { get; set; }
        public string diagEndoDisDesc { get; set; }
        public string endoOther { get; set; }
        public string endoOtherDesc { get; set; }
        public string muscDeny { get; set; }
        public string backPain { get; set; }
        public string jointPain { get; set; }
        public string arthritis { get; set; }
        public string muscRigid { get; set; }
        public string breaks { get; set; }
        public string boneDisease { get; set; }
        public string muscWeakness { get; set; }
        public string muscOther { get; set; }
        public string muscOtherDesc { get; set; }
        public string femRepNA { get; set; }
        public string femRepDeny { get; set; }
        public string suspPreg { get; set; }
        public string preg { get; set; }
        public string pregMonths { get; set; }
        public string birthControl { get; set; }
        public string birthControlType { get; set; }
        public string femRepOther { get; set; }
        public string femRepOtherDesc { get; set; }
        public string menstNa { get; set; }
        public string menstDeny { get; set; }
        public string regMenst { get; set; }
        public string dysmen { get; set; }
        public string amenorrhea { get; set; }
        public string menstOther { get; set; }
        public string menstOtherDesc { get; set; }
        public string lMP { get; set; }
        public string maleRepNA { get; set; }
        public string maleRepDeny { get; set; }
        public string maleDischarge { get; set; }
        public string maleHesitancy { get; set; }
        public string maleImpotent { get; set; }
        public string maleProstateProb { get; set; }
        public string maleRepOther { get; set; }
        public string maleRepOtherDesc { get; set; }
        public string concernReturnRes { get; set; }
        public string concernReturnResDesc { get; set; }
        public string physicalDeny { get; set; }
        public string physicalImpGait { get; set; }
        public string physicalTransDiff { get; set; }
        public string physicalBedImm { get; set; }
        public string physicalStanding { get; set; }
        public string physicalFatigue { get; set; }
        public string physicalAssistDev { get; set; }
        public string physicalGenWeak { get; set; }
        public string occuDeny { get; set; }
        public string occuDressing { get; set; }
        public string occuBathing { get; set; }
        public string occuFeeding { get; set; }
        public string occuGrooming { get; set; }
        public string occuToilet { get; set; }
        public string occuOther { get; set; }
        public string occuOtherDesc { get; set; }
        public string swalDeny { get; set; }
        public string swalDiffSwal { get; set; }
        public string swalCoughAfter { get; set; }
        public string swalCoughWhile { get; set; }
        public string swalHistAsp { get; set; }
        public string swalDrool { get; set; }
        public string swalOther { get; set; }
        public string swalOtherDesc { get; set; }
        public string sleepAvg { get; set; }
        public string sleepDeny { get; set; }
        public string sleepInsom { get; set; }
        public string sleepEarlyAwake { get; set; }
        public string sleepNightAwake { get; set; }
        public string sleepReqMed { get; set; }
        public string sleepNightmares { get; set; }
        public string sleepOther { get; set; }
        public string sleepOtherDesc { get; set; }
        public string visDeny { get; set; }
        public string visBlurry { get; set; }
        public string visGlasses { get; set; }
        public string visContacts { get; set; }
        public string visImpair { get; set; }
        public string visLegBlind { get; set; }
        public string visOther { get; set; }
        public string visOtherDesc { get; set; }
        public string hearDeny { get; set; }
        public string hearEarPain { get; set; }
        public string hearAid { get; set; }
        public string hearImpair { get; set; }
        public string hearDeaf { get; set; }
        public string hearSignLang { get; set; }
        public string hearRing { get; set; }
        public string hearOther { get; set; }
        public string hearOtherDesc { get; set; }
        public string canPatRead { get; set; }
        public string canPatWrite { get; set; }
        public string gradeYesNo { get; set; }
        public string gradeDesc { get; set; }
        public string gED { get; set; }
        public string yearsCollege { get; set; }
        public string yearsCollegeDesc { get; set; }
        public string degEarned { get; set; }
        public string learnChalCog { get; set; }
        public string learnChalEmo { get; set; }
        public string learnChalPoorCop { get; set; }
        public string learnChalImpThought { get; set; }
        public string learnChalLangBar { get; set; }
        public string learnChalSenseImpair { get; set; }
        public string learnChalDeny { get; set; }
        public string learnChalOther { get; set; }
        public string learnChalOtherDesc { get; set; }
        public string learnPrefWrit { get; set; }
        public string learnPrefVerb { get; set; }
        public string learnPrefDemo { get; set; }
        public string learnPrefVideo { get; set; }
        public string learnPrefAudio { get; set; }
        public string learnPrefHands { get; set; }
        public string feelAboutHospitalized { get; set; }
        public string issueBroughtHosp { get; set; }
        public string iDSuppLife { get; set; }
        public string methSuccessManage { get; set; }
        public string duringStayHelp { get; set; }
        public string spiritReligCultPrac { get; set; }
        public string spiritReligCultPracDesc { get; set; }
        public string nutScore { get; set; }
        public string nutDeny { get; set; }
        public string nutMedPreg { get; set; }
        public string nutMedAnem { get; set; }
        public string nutMedCirr { get; set; }
        public string nutMedHiv { get; set; }
        public string nutMedHyperten { get; set; }
        public string nutMedHyperlip { get; set; }
        public string nutMedOther { get; set; }
        public string nutMedOtherDesc { get; set; }
        public string nutDiabetes { get; set; }
        public string nutUnderWei { get; set; }
        public string nutBingPurg { get; set; }
        public string nutVomit { get; set; }
        public string nutDiarr { get; set; }
        public string nutCultDiet { get; set; }
        public string nutCultDesc { get; set; }
        public string nutChewDiff { get; set; }
        public string dietConsultOrder { get; set; }
        public string fluidIntake { get; set; }
        public string complaintThirst { get; set; }
        public string stickyMembrane { get; set; }
        public string amberUrine { get; set; }
        public string lossSkin { get; set; }
        public string dryFlakySkin { get; set; }
        public string sunkEyes { get; set; }
        public string dehydrationOther { get; set; }
        public string dehydrationOtherDesc { get; set; }
        public string bMIScore { get; set; }
        public string bMIL19G30 { get; set; }
        public string bMIAgreeAssess { get; set; }
        public string suicideSrcPatient { get; set; }
        public string suicideSrcFamily { get; set; }
        public string suicideSrcFamilyDesc { get; set; }
        public string suicideSrcOther { get; set; }
        public string suicideSrcOtherDesc { get; set; }
        public string presentSelfInj { get; set; }
        public string presentSelfInjDesc { get; set; }
        public string appearSelfInf { get; set; }
        public string appearSelfInfDesc { get; set; }
        public string wishDead { get; set; }
        public string wishDeadDesc { get; set; }
        public string thoughtKillSelf { get; set; }
        public string thoughtKillSelfDesc { get; set; }
        public string thoughtKillsSelfIntent { get; set; }
        public string thoughtKillSelfIntentDesc { get; set; }
        public string thoughtKillSelfHow { get; set; }
        public string thoughtKillSelfHowDesc { get; set; }
        public string workedOutKillSelf { get; set; }
        public string workedOutKillSelfDesc { get; set; }
        public string thinkActThoughts { get; set; }
        public string thinkActThoughtsDesc { get; set; }
        public string thoughtsFrighten { get; set; }
        public string thoughtsFrightenDesc { get; set; }
        public string haveOwnLethal { get; set; }
        public string haveOwnLethalType { get; set; }
        public string haveOwnLethalWhere { get; set; }
        public string haveOwnLethalWho { get; set; }
        public string madeSuicideAttempt { get; set; }
        public string madeSuicideAttemptDesc { get; set; }
        public string stoppedAttempt { get; set; }
        public string stoppedAttemptDesc { get; set; }
        public string attemptAroundPpl { get; set; }
        public string attemptAroundPplDesc { get; set; }
        public string diagSchiz { get; set; }
        public string diagSchizDesc { get; set; }
        public string closeAttemptSuicide { get; set; }
        public string closeAttemptSuicideDesc { get; set; }
        public string histSexAbuse { get; set; }
        public string histSexAbuseWho { get; set; }
        public string histSexAbuseWhen { get; set; }
        public string histSubAbuse { get; set; }
        public string histSubAbuseDesc { get; set; }
        public string intentHurtUpset { get; set; }
        public string intentHurtUpsetDesc { get; set; }
        public string highLevelStress { get; set; }
        public string highLevelStressDesc { get; set; }
        public string hopelessHelpless { get; set; }
        public string hopelessHelplessDesc { get; set; }
        public string withdrawnLately { get; set; }
        public string withdrawnLatelyDesc { get; set; }
        public string stressorsList { get; set; }
        public string stressorsLossDig { get; set; }
        public string importantPeople { get; set; }
        public string whoTellAnything { get; set; }
        public string skillsProud { get; set; }
        public string otherProtFact { get; set; }
        public string clinPresStress { get; set; }
        public string clinPresDep { get; set; }
        public string clinPresNoHope { get; set; }
        public string clinPresBurden { get; set; }
        public string clinPresNeg { get; set; }
        public string clinPresOther { get; set; }
        public string clinPresOtherDesc { get; set; }
        public string engageCredible { get; set; }
        public string engageCoop { get; set; }
        public string engageRelieved { get; set; }
        public string engageSeekHelp { get; set; }
        public string riskStatusRad { get; set; }
        public string riskStatusWhy { get; set; }
        public string riskStateRad { get; set; }
        public string riskStateWhy { get; set; }
        public string riskStateTrig { get; set; }
        public string internalCopeStrat { get; set; }
        public string internalCopeRad { get; set; }
        public string activeDistract { get; set; }
        public string activeDistractRad { get; set; }
        public string talkLovedOut { get; set; }
        public string talkLovedOutRad { get; set; }
        public string seekStaff { get; set; }
        public string seekStafRad { get; set; }
        public string noResIdenOrAvail { get; set; }
        public string adultFallScore { get; set; }
        public string childAdolFallScore { get; set; }
        public string elopeScore { get; set; }
        public string elopeIntent { get; set; }
        public string elopeHist { get; set; }
        public string elopeTest { get; set; }
        public string elopeSubAbuse { get; set; }
        public string elopeUnpredict { get; set; }
        public string elopeInvolun { get; set; }
        public string elopePsychotic { get; set; }
        public string homAssultVioScore { get; set; }
        public string homAssultStrike { get; set; }
        public string homAssultVerbThreat { get; set; }
        public string homAssultHist { get; set; }
        public string homAssultAdmitHI { get; set; }
        public string homAssultParaDelus { get; set; }
        public string homAssultManic { get; set; }
        public string homAssultUnpredict { get; set; }
        public string homAssultPsychotic { get; set; }
        public string sexActOutScore { get; set; }
        public string sexActPredator { get; set; }
        public string sexActHyper { get; set; }
        public string sexActPoorBound { get; set; }
        public string sexActHist { get; set; }
        public string sexActImpulse { get; set; }
        public string sexActManic { get; set; }
        public string sexActPromis { get; set; }
        public string sexActExplicit { get; set; }
        public string vulnerRiskScore { get; set; }
        public string vulnerRiskVisHear { get; set; }
        public string vulnerRiskDelay { get; set; }
        public string vulnerRiskHist { get; set; }
        public string vulnerRiskConfus { get; set; }
        public string vulnerRiskFrail { get; set; }
        public string vulnerRiskWand { get; set; }
        public string vulnerRiskVerbProv { get; set; }
        public string vulnerRiskMobil { get; set; }
        public string wdAlcoh { get; set; }
        public string wdBenzo { get; set; }
        public string wdAlcBenzDeny7 { get; set; }
        public string wdAlcBenzAdmitRecent { get; set; }
        public string wdAlcBenzDenySympt { get; set; }
        public string wdAlcBenzNausVom { get; set; }
        public string wdAlcBenzTremors { get; set; }
        public string wdAlcBenzSweats { get; set; }
        public string wdAlcBenzAnxiety { get; set; }
        public string wdAlcBenzHeadAche { get; set; }
        public string wdAlcBenzAgitated { get; set; }
        public string wdAlcBenzDisoriented { get; set; }
        public string wdAlcBenzTactile { get; set; }
        public string wdAlcBenzAuditory { get; set; }
        public string wdAlcBenzVisual { get; set; }
        public string wdCocaineDeny7 { get; set; }
        public string wdCocaineAdmitRecent { get; set; }
        public string wdCocaineDenySympt { get; set; }
        public string wdCocaineAgitated { get; set; }
        public string wdCocaineDep { get; set; }
        public string wdCocaineAnxiety { get; set; }
        public string wdCocaineExFatigue { get; set; }
        public string wdCocaineAngryBurst { get; set; }
        public string wdCocaineTremors { get; set; }
        public string wdCocaineMuscAche { get; set; }
        public string wdCocaineCramps { get; set; }
        public string wdCocainePain { get; set; }
        public string wdCocaineDistSleep { get; set; }
        public string wdCocaineNausVom { get; set; }
        public string wdOpiDeny7 { get; set; }
        public string wdOpiAdmitRecent { get; set; }
        public string wdOpiDenySympt { get; set; }
        public string wdOpiSweat { get; set; }
        public string wdOpiDialPupils { get; set; }
        public string wdOpiWateryEyes { get; set; }
        public string wdOpiSneezRunNose { get; set; }
        public string wdOpiHighBP { get; set; }
        public string wdOpiGooseBmp { get; set; }
        public string wdOpiMuscAche { get; set; }
        public string wdOpiInsom { get; set; }
        public string wdOpiNausVom { get; set; }
        public string wdOpiDiarrhea { get; set; }
        public string wdMethDeny7 { get; set; }
        public string wdMethAdmitRecent { get; set; }
        public string wdMethDenySympt { get; set; }
        public string wdMethFatigue { get; set; }
        public string wdMethDistSleep { get; set; }
        public string wdMethIrritable { get; set; }
        public string wdMethIntenseHun { get; set; }
        public string wdMethDepMood { get; set; }
        public string wdMethAnxiety { get; set; }
        public string wdMethPsychSympt { get; set; }
        public string wdMarjDeny7 { get; set; }
        public string wdMarjAdmitRecent { get; set; }
        public string wdMarjDenySympt { get; set; }
        public string wdMarjIrritable { get; set; }
        public string wdMarjPhysicalTension { get; set; }
        public string wdMarjDecAppetite { get; set; }
        public string wdMarjDepMood { get; set; }
        public string wdMarjStomAche { get; set; }
        public string wdMarjRestless { get; set; }
        public string wdMarjInsom { get; set; }
        public string wdMarjAggresive { get; set; }
        public string wdMarjAnger { get; set; }
        public string wdMarjStrngeDream { get; set; }
        public string wdMarjAnxiety { get; set; }
        public string berDoSnore { get; set; }
        public string berSnoreIs { get; set; }
        public string berOftenSnore { get; set; }
        public string berSnoreBotherPeople { get; set; }
        public string berNoticeQuitBreath { get; set; }
        public string berOftenTired { get; set; }
        public string berWalkTired { get; set; }
        public string berNodOffDrive { get; set; }
        public string berNodOffDriveOften { get; set; }
        public string berHighBP { get; set; }
        public string berCat1Total { get; set; }
        public string berCat1Result { get; set; }
        public string berNum8Occur { get; set; }
        public string berCat2Total { get; set; }
        public string berCat2Result { get; set; }
        public string berCat3Result { get; set; }
        public string berCat3Risk { get; set; }
        public string berCat3ConsultReq { get; set; }
        public string cigarettes { get; set; }
        public string cigarettesValue { get; set; }
        public string cigars { get; set; }
        public string cigarsValue { get; set; }
        public string pipeSmoke { get; set; }
        public string pipeSmokeValue { get; set; }
        public string chew { get; set; }
        public string chewValue { get; set; }
        public string tobaccoOther { get; set; }
        public string tobaccoOtherDesc { get; set; }
        public string tobaccoOtherValue { get; set; }
        public string tobRevDanger { get; set; }
        public string tobRevCop { get; set; }
        public string tobRevInfo { get; set; }
        public string tobOther { get; set; }
        public string tobOtherDesc { get; set; }
        public string tobNotOffered { get; set; }
        public string tobPtRefused { get; set; }
        public string offTobCess { get; set; }
        public string yesPhysNotified { get; set; }
        public string tobMedContPatAllFDA { get; set; }
        public string tobMedContDrugInter { get; set; }
        public string tobMedContOther { get; set; }
        public string tobMedContOtherDesc { get; set; }
        public string nameRelatNurseAssess { get; set; }
        public string yr58Bath { get; set; }
        public string yr58Chores { get; set; }
        public string yr58Coop { get; set; }
        public string yr58Needs { get; set; }
        public string yr58MinResp { get; set; }
        public string yr912BestFriend { get; set; }
        public string yr912AttSpan { get; set; }
        public string yr912Hobby { get; set; }
        public string yr912FamDec { get; set; }
        public string yr912RespSelf { get; set; }
        public string yr1315ShowsConc { get; set; }
        public string yr1315ExpressAff { get; set; }
        public string yr1315CompThought { get; set; }
        public string yr1315GroupSports { get; set; }
        public string yr1618Interest { get; set; }
        public string yr1618LessParents { get; set; }
        public string yr1618InterestSex { get; set; }
        public string yr1618ReasChoice { get; set; }
        public string patientAwayHome { get; set; }
        public string immuneUpToDate { get; set; }
        public string birthDefects { get; set; }
        public string birthDefectsDesc { get; set; }
        public string histDevDelay { get; set; }
        public string histDevDelayDesc { get; set; }
        public string parGuardExpect { get; set; }
        public string nurseAdminNote { get; set; }
        public string nurseSig1 { get; set; }
        public Nullable<System.DateTime> nurseSig1Date { get; set; }
        public string nurseSig1Time { get; set; }
        public string nurseSig2 { get; set; }
        public Nullable<System.DateTime> nurseSig2Date { get; set; }
        public string nurseSigTime { get; set; }
        public string aSWAssignWorker { get; set; }
        public Nullable<System.DateTime> aSWDateComplete { get; set; }
        public string aSWLegStat { get; set; }
        public string aSWLegStatDesc { get; set; }
        public string aSWSrcInfo { get; set; }
        public string aSWReliableSrc { get; set; }
        public string aSWReliableSrcDesc { get; set; }
        public string aSWNaturePresProb { get; set; }
        public string aSWCurLevFuncDifTypFunc { get; set; }
        public string aSWPatDescSelfSomeone { get; set; }
        public string aSWFamSupDescPat { get; set; }
        public string aSWCommInvolve { get; set; }
        public string aSWDangerSelfNotPres { get; set; }
        public string aSWDangerSelfCurrent { get; set; }
        public string aSWDangerSelfHistory { get; set; }
        public string aSWDangerSelfIdeation { get; set; }
        public string aSWDangerSelfPlan { get; set; }
        public string aSWDangerSelfAttempt { get; set; }
        public string aSWDangerSelfIntent { get; set; }
        public string aSWDangerOthersNotPres { get; set; }
        public string aSWDangerOthersCurrent { get; set; }
        public string aSWDangerOthersHistory { get; set; }
        public string aSWDangerOthersIdeation { get; set; }
        public string aSWDangerOthersPlan { get; set; }
        public string aSWDangerOthersAttempt { get; set; }
        public string aSWDangerOthersIntent { get; set; }
        public string aSWDangerDesc { get; set; }
        public string aSWLethPriorMeans { get; set; }
        public string aSWPastSelfInj { get; set; }
        public string aSWPastSelfInjDesc { get; set; }
        public string aSWWeaponLethMeans { get; set; }
        public string aSWWeaponLethMeansRemovePlan { get; set; }
        public string aSWEduPosRisk { get; set; }
        public string aSWResponsePat { get; set; }
        public Nullable<System.DateTime> aSWResponsePatDate { get; set; }
        public string aSWResponsePatTime { get; set; }
        public string aSWVerify { get; set; }
        public Nullable<System.DateTime> aSWVerifyDate { get; set; }
        public string aSWVerifyTime { get; set; }
        public string aSWSexAbuseVict { get; set; }
        public string aSWSexAbusePerp { get; set; }
        public string aSWSexAbuseWitness { get; set; }
        public string aSWSexAbuseWitnessDesc { get; set; }
        public string aSWSexAbuseReport { get; set; }
        public string aSWSexAbuseReportDesc { get; set; }
        public string aSWPhysAbuseVict { get; set; }
        public string aSWPhysAbusePerp { get; set; }
        public string aSWPhysAbuseWitness { get; set; }
        public string aSWPhsyAbuseWitnessDesc { get; set; }
        public string aSWPhsyAbuseReport { get; set; }
        public string aSWPhsyAbuseReportDesc { get; set; }
        public string aSWEmoNegAbuseVict { get; set; }
        public string aSWEmoNegAbusePerp { get; set; }
        public string aSWEmoNegAbuseWitness { get; set; }
        public string aSWEmoNegAbuseWitnessDesc { get; set; }
        public string aSWEmoNegAbuseReported { get; set; }
        public string aSWEmoNegAbuseReportedDesc { get; set; }
        public string aSWOtherTraumaExp { get; set; }
        public string aSWHomePrior { get; set; }
        public string aSWRetHome { get; set; }
        public string aSWRetHomeWhom { get; set; }
        public string aSWRetHomeWhen { get; set; }
        public string aSWHomePlanDisch { get; set; }
        public string aSWSafeHome { get; set; }
        public string aSWSafeHomeDesc { get; set; }
        public string aSWMaritStat { get; set; }
        public Nullable<System.DateTime> aSWDateChange { get; set; }
        public string aSWCurrPreg { get; set; }
        public string aSWTermPreg { get; set; }
        public string aSWTermPregDesc { get; set; }
        public string aSWMemHelpful { get; set; }
        public string aSWMemHelpfulDesc { get; set; }
        public string aSWRelatProb { get; set; }
        public Nullable<System.DateTime> aSWDateFamSess { get; set; }
        public string aSWFamSessInvite { get; set; }
        public string aSWFamDeclineReason { get; set; }
        public string aSWPriorFamInvolve { get; set; }
        public string aSWRecFamInvolve { get; set; }
        public string aSWProbImpactFam { get; set; }
        public string aSWProbImpactFamDesc { get; set; }
        public string aSWHistHomSuic { get; set; }
        public string aSWHistHomSuicDesc { get; set; }
        public string aSWMedAdhPat { get; set; }
        public string aSWMedAdhTreat { get; set; }
        public string aSWHospPrev { get; set; }
        public string aSWHospPrevRemainComm { get; set; }
        public string aSWEffIneffTreatment { get; set; }
        public string aSWDvlpNone { get; set; }
        public string aSWDvlpGambling { get; set; }
        public string aSWDvlpShopping { get; set; }
        public string aSWDvlpEmoEat { get; set; }
        public string aSWDvlpCleanOrg { get; set; }
        public string aSWDvlpHoardCollect { get; set; }
        public string aSWDvlpOther { get; set; }
        public string aSWDvlpOtherDesc { get; set; }
        public string aSWDvlpExplain { get; set; }
        public string aSWHistArrest { get; set; }
        public string aSWHistArrestDesc { get; set; }
        public string aSWOtherLegal { get; set; }
        public string aSWOtherLegalDesc { get; set; }
        public string aSWCurrSchool { get; set; }
        public string aSWCurrSchoolWhere { get; set; }
        public string aSWSchoolStress { get; set; }
        public string aSWSchoolStressDesc { get; set; }
        public string aSWHighestEduComplete { get; set; }
        public string aSWDesireFutEdu { get; set; }
        public string aSWSubAbuseNA { get; set; }
        public string aSWIncDrugAlc { get; set; }
        public string aSWSubAbuseResultArrest { get; set; }
        public string aSWSubAbuseResultRelatProb { get; set; }
        public string aSWSubAbuseResultUnpBills { get; set; }
        public string aSWSubAbuseResultThoughtSelfHarm { get; set; }
        public string aSWSubAbuseResultBlackout { get; set; }
        public string aSWSubAbuseResultWorkProb { get; set; }
        public string aSWSubAbuseResultPromis { get; set; }
        public string aSWSubAbuseResultOther { get; set; }
        public string aSWSubAbuseResultOtherDesc { get; set; }
        public string aSWSubAbuseResultNone { get; set; }
        public string aSWSeeUseProb { get; set; }
        public string aSWDrugChoice { get; set; }
        public string aSWBenefitUse { get; set; }
        public string aSWSubTreatHist { get; set; }
        public string aSWSubTreatHistDesc { get; set; }
        public string aSWFeedback { get; set; }
        public string aSWDiscNegCons { get; set; }
        public string aSWDiscSeverity { get; set; }
        public string aSWMotDisc { get; set; }
        public string aSWAdvAbstain { get; set; }
        public string aSWInterventionOther { get; set; }
        public string aSWInterventionOtherDesc { get; set; }
        public string aSWRecom { get; set; }
        public string aSWRecomDesc { get; set; }
        public string aSWPatInformRecom { get; set; }
        public string aSWEduProvPat { get; set; }
        public string aSWReferMade { get; set; }
        public string aSWReferMadeDesc { get; set; }
        public string aSWEmpStress { get; set; }
        public string aSWFeelCurrWork { get; set; }
        public string aSWFeelCurrWorkDesc { get; set; }
        public string aSWAvgMonIncome { get; set; }
        public string aSWSrcIncome { get; set; }
        public string aSWInvolvMilitary { get; set; }
        public string aSWMilBranch { get; set; }
        public string aSWMilDates { get; set; }
        public string aSWMilDischar { get; set; }
        public string aSWMilDepAwayHome { get; set; }
        public string aSWMilEngageCombat { get; set; }
        public string aSWMilSigEvents { get; set; }
        public string aSWEligVABenefits { get; set; }
        public string aSWFinanceStress { get; set; }
        public string aSWFinanceStressDesc { get; set; }
        public string aSWMeetBasicNeeds { get; set; }
        public string aSWMedIssContrib { get; set; }
        public string aSWMedIssContribDesc { get; set; }
        public string aSWHistSigMedIss { get; set; }
        public string aSWHistSigMedIssDesc { get; set; }
        public string aSWChronDisabImpFunct { get; set; }
        public string aSWChronDisabImpFunctDesc { get; set; }
        public string aSWChangReligInvo { get; set; }
        public string aSWCurrReligInvo { get; set; }
        public string aSWCultIssContrib { get; set; }
        public string aSWCultIssContribDesc { get; set; }
        public string aSWWeNeedKnow { get; set; }
        public string aSWWeNeedKnowDesc { get; set; }
        public string aSWCareHIstNonComp { get; set; }
        public string aSWCareHouse { get; set; }
        public string aSWCarePetsUnsup { get; set; }
        public string aSWCareTrans { get; set; }
        public string aSWCareAcuteMed { get; set; }
        public string aSWCareNone { get; set; }
        public string aSWCareOther { get; set; }
        public string aSWCareOtherDesc { get; set; }
        public string aSWReadmNA { get; set; }
        public string aSWReadmMedStab { get; set; }
        public string aSWReadmPriorAuthor { get; set; }
        public string aSWReadmCompli { get; set; }
        public string aSWReadmOther { get; set; }
        public string aSWReadmOtherDesc { get; set; }
        public string aSWMAPartCommSupp { get; set; }
        public string aSWMAPartCommSuppWhen { get; set; }
        public string aSWMAPartCommSuppResp { get; set; }
        public string aSWObtMedTrans { get; set; }
        public string aSWObtMedIncome { get; set; }
        public string aSWObtMedNeed { get; set; }
        public string aSWObtMedNeedDesc { get; set; }
        public string aSWArrSchedPersVeh { get; set; }
        public string aSWArrSchedFamFri { get; set; }
        public string aSWArrSchedMATP { get; set; }
        public string aSWArrSchedNeed { get; set; }
        public string aSWArrSchedNeedDesc { get; set; }
        public string aSWPrefPharm { get; set; }
        public string aSWConcernFollowPlan { get; set; }
        public string aSWBarTrans { get; set; }
        public string aSWBarMeds { get; set; }
        public string aSWBarHouse { get; set; }
        public string aSWBarNonComp { get; set; }
        public string aSWBarAbsFacAccSpecNeed { get; set; }
        public string aSWBarOther { get; set; }
        public string aSWBarOtherDesc { get; set; }
        public string aSWBarNone { get; set; }
        public string aSWReferOutpat { get; set; }
        public string aSWReferPsych { get; set; }
        public string aSWReferPHP { get; set; }
        public string aSWReferPsychRehab { get; set; }
        public string aSWReferIOP { get; set; }
        public string aSWReferLTSRCRR { get; set; }
        public string aSWReferEAC { get; set; }
        public string aSWReferStateHosp { get; set; }
        public string aSWReferCMBCM { get; set; }
        public string aSWReferInpatDA { get; set; }
        public string aSWReferPCP { get; set; }
        public string aSWReferOutpatDA { get; set; }
        public string aSWReferPeerSpec { get; set; }
        public string aSWReferOther { get; set; }
        public string aSWReferOtherDesc { get; set; }
        public string aSWReferNone { get; set; }
        public string aSWConcRecom { get; set; }
        public string aSWRoleGrpTher { get; set; }
        public string aSWRoleIndivTher { get; set; }
        public string aSWRoleFamTher { get; set; }
        public string aSWRoleAftercare { get; set; }
        public string aSWRoleOther { get; set; }
        public string aSWRoleOtherDesc { get; set; }
        public string aSWPrelimDischargePlan { get; set; }
        public Nullable<System.DateTime> aSWStaffSigDate { get; set; }
        public string aSWStaffSigTime { get; set; }
        public string cSWSocialWorker { get; set; }
        public Nullable<System.DateTime> cSWDateComplete { get; set; }
        public string cSWLegalGardNa { get; set; }
        public string cSWLegalGardDesc { get; set; }
        public string cSWLegStat { get; set; }
        public string cSWLegStatDesc { get; set; }
        public string cSWSrcInfo { get; set; }
        public string cSWSrcReliab { get; set; }
        public string cSWSrcReliabDesc { get; set; }
        public string cSWNaturePresProb { get; set; }
        public string cSWLevFuncDifTyp { get; set; }
        public string cSWPatDescElse { get; set; }
        public string cSWCareDescPat { get; set; }
        public string cSWCommInv { get; set; }
        public string cSWDanSelfNot { get; set; }
        public string cSWDanSelfCurr { get; set; }
        public string cSWDanSelfHist { get; set; }
        public string cSWDanSelfIdea { get; set; }
        public string cSWDanSelfPlan { get; set; }
        public string cSWDanSelfAtt { get; set; }
        public string cSWDanSelfInte { get; set; }
        public string cSWDanOthNot { get; set; }
        public string cSWDanOthCurr { get; set; }
        public string cSWDanOthHist { get; set; }
        public string cSWDanOthIdea { get; set; }
        public string cSWDanOthPlan { get; set; }
        public string cSWDanOthAtt { get; set; }
        public string cSWDanOthInte { get; set; }
        public string cSWDanDesc { get; set; }
        public string cSWLethPriorMean { get; set; }
        public string cSWPastSelfInj { get; set; }
        public string cSWPastSelfInjDesc { get; set; }
        public string cSWWeapHome { get; set; }
        public string cSWWeapPlanDesc { get; set; }
        public string cSWEduRiskWeap { get; set; }
        public string cSWRespPt { get; set; }
        public Nullable<System.DateTime> cSWRespDatePt { get; set; }
        public string cSWRespTimePt { get; set; }
        public string cSWVerif { get; set; }
        public Nullable<System.DateTime> cSWVerifDate { get; set; }
        public string cSWVerifTime { get; set; }
        public string cSWSexAbuseVict { get; set; }
        public string cSWSexAbusePerp { get; set; }
        public string cSWSexAbuseWitness { get; set; }
        public string cSWSexAbuseWitnessDesc { get; set; }
        public string cSWSexAbuseReport { get; set; }
        public string cSWSexAbuseReportDesc { get; set; }
        public string cSWPsyAbuseVict { get; set; }
        public string cSWPsyAbusePerp { get; set; }
        public string cSWPsyAbuseWitness { get; set; }
        public string cSWPsyAbuseWitnessDesc { get; set; }
        public string cSWPsyAbuseReport { get; set; }
        public string cSWPsyAbuseReportDesc { get; set; }
        public string cSWEmoNegAbuseVict { get; set; }
        public string cSWEmoNegAbusePerp { get; set; }
        public string cSWEmoNegAbuseWitness { get; set; }
        public string cSWEmoNegAbuseWitnessDesc { get; set; }
        public string cSWEmoNegAbuseReport { get; set; }
        public string cSWEmoNegAbuseReportDesc { get; set; }
        public string cSWOthTraumaExp { get; set; }
        public string cSWHomePriorAdmin { get; set; }
        public string cSWRetHome { get; set; }
        public string cSWRetHomeWhom { get; set; }
        public string cSWRetHomeWhen { get; set; }
        public string cSWCarePlanDisch { get; set; }
        public string cSWSafeHome { get; set; }
        public string cSWSafeHomeDesc { get; set; }
        public string cSWSexAct { get; set; }
        public string cSWSexActAge { get; set; }
        public string cSWSexActNumPart { get; set; }
        public string cSWSexActPreg { get; set; }
        public string cSWSexActPregTimes { get; set; }
        public string cSWSexActPregNumChi { get; set; }
        public string cSWSigRelat { get; set; }
        public string cSWParentMaritStat { get; set; }
        public Nullable<System.DateTime> cSWParentMaritStatDate { get; set; }
        public string cSWPrimeCaregiver { get; set; }
        public string cSWVisitArrange { get; set; }
        public string cSWMemHelpPat { get; set; }
        public string cSWMemHelpPatDesc { get; set; }
        public string cSWRelatProbMem { get; set; }
        public Nullable<System.DateTime> cSWFamSessDate { get; set; }
        public string cSWFamSessInvite { get; set; }
        public string cSWFamSessDeclineReason { get; set; }
        public string cSWLevFamInvPrior { get; set; }
        public string cSWRecommFamInvAfter { get; set; }
        public string cSWCarFeelPatDifBehav { get; set; }
        public string cSWCarFeelPatDifBehavDesc { get; set; }
        public string cSWHistCYS { get; set; }
        public string cSWHistCYSDesc { get; set; }
        public string cSWFamMemAbuImp { get; set; }
        public string cSWFamMemAbuImpDesc { get; set; }
        public string cSWHistHomSuic { get; set; }
        public string cSWHistHomSuicDesc { get; set; }
        public string cSWPatPartTreat { get; set; }
        public string cSWPatMedPat { get; set; }
        public string cSWPatMedTreatProv { get; set; }
        public string cSWPatHospPrev { get; set; }
        public string cSWHospPrevHelpCommInvo { get; set; }
        public string cSWHosp30ContribReadmin { get; set; }
        public string cSWEffIneffTreatHist { get; set; }
        public string cSWIncUseSubstance { get; set; }
        public string cSWSubResultArrest { get; set; }
        public string cSWSubResultRelatProb { get; set; }
        public string cSWSubResultUnpaidBills { get; set; }
        public string cSWSubResultThoughtSelfHarm { get; set; }
        public string cSWSubResultBlackout { get; set; }
        public string cSWSubResultWorkProb { get; set; }
        public string cSWSubResultPromisc { get; set; }
        public string cSWSubResultOther { get; set; }
        public string cSWSubResultOtherDesc { get; set; }
        public string cSWSubResultNone { get; set; }
        public string cSWSeeUseProb { get; set; }
        public string cSWDrugChoice { get; set; }
        public string cSWReasonUse { get; set; }
        public string cSWSubAbuseTreatHist { get; set; }
        public string cSWInterventions { get; set; }
        public string cSWSubAbuseRecommNA { get; set; }
        public string cSWSubAbuseRecommDesc { get; set; }
        public string cSWPatInformRecomm { get; set; }
        public string cSWEduProvPat { get; set; }
        public string cSWFamInformRecomm { get; set; }
        public string cSWEduProvFam { get; set; }
        public string cSWReferMade { get; set; }
        public string cSWReferMadeDesc { get; set; }
        public string cSWHistArrest { get; set; }
        public string cSWHistArrestDesc { get; set; }
        public string cSWOthLegIss { get; set; }
        public string cSWOthLegIssDesc { get; set; }
        public string cSWTimeCurrSchool { get; set; }
        public string cSWNumSchoolAtt { get; set; }
        public string cSWPatFeelSchTeach { get; set; }
        public string cSWPatFeelClassmates { get; set; }
        public string cSWSigChanSocAca { get; set; }
        public string cSWSigChanSocAcaDesc { get; set; }
        public string cSWDetSuspensTruancy { get; set; }
        public string cSWDetSuspensTruancyDesc { get; set; }
        public string cSWWorking { get; set; }
        public string cSWWorkingHoursWeek { get; set; }
        public string cSWWorkingFeelings { get; set; }
        public string cSWParMilit { get; set; }
        public string cSWParMilitDesc { get; set; }
        public string cSWParMilitDeploy { get; set; }
        public string cSWBasicNeedMet { get; set; }
        public string cSWMedIssContrib { get; set; }
        public string cSWMedIssContribDesc { get; set; }
        public string cSWChronPainDisabImpFunct { get; set; }
        public string cSWChronPainDisabImpFunctDesc { get; set; }
        public string cSWHistSigMedIss { get; set; }
        public string cSWHistSigMedIssDesc { get; set; }
        public string cSWEatDepBored { get; set; }
        public string cSWEatDepBoredDesc { get; set; }
        public string cSWCurrStatedFeelBody { get; set; }
        public string cSWChangeReligInvolv { get; set; }
        public string cSWChangeReligInvolvDesc { get; set; }
        public string cSWCultIssContribProb { get; set; }
        public string cSWCultIssContribProbDesc { get; set; }
        public string cSWCultOther { get; set; }
        public string cSWCultOtherDesc { get; set; }
        public string cSWAssessNeed { get; set; }
        public string cSWMACommSuppServ { get; set; }
        public string cSWMACommSuppServWhen { get; set; }
        public string cSWMACommSuppServResponse { get; set; }
        public string cSWObtMed { get; set; }
        public string cSWPrefPharm { get; set; }
        public string cSWConcernFollDisch { get; set; }
        public string cSWHowArriveSchedAppoint { get; set; }
        public string cSWBarTransport { get; set; }
        public string cSWBarCostMed { get; set; }
        public string cSWBarHousing { get; set; }
        public string cSWBarHisNonComp { get; set; }
        public string cSWBarAbsFacSpecNeed { get; set; }
        public string cSWBarOther { get; set; }
        public string cSWBarOtherDesc { get; set; }
        public string cSWBarNone { get; set; }
        public string cSWRefOutpat { get; set; }
        public string cSWRefPsychia { get; set; }
        public string cSWRefPHP { get; set; }
        public string cSWRefTFCCRR { get; set; }
        public string cSWRefRTF { get; set; }
        public string cSWRefBHRS { get; set; }
        public string cSWRefFB { get; set; }
        public string cSWRefMST { get; set; }
        public string cSWRefCMBCM { get; set; }
        public string cSWRefInpatDA { get; set; }
        public string cSWRefPCP { get; set; }
        public string cSWRefOutpatDA { get; set; }
        public string cSWRefNeuro { get; set; }
        public string cSWRefOther { get; set; }
        public string cSWRefOtherDesc { get; set; }
        public string cSWRefNone { get; set; }
        public string cSWClinConcRecomm { get; set; }
        public string cSWSWGroup { get; set; }
        public string cSWSWIndiv { get; set; }
        public string cSWSWFamily { get; set; }
        public string cSWSWAftercare { get; set; }
        public string cSWSWOther { get; set; }
        public string cSWSWOtherDesc { get; set; }
        public string cSWPreDisch { get; set; }
        public Nullable<System.DateTime> cSWStaffSigDate { get; set; }
        public string cSWStaffSigTime { get; set; }
    }  
}
