//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class deffered_problem_list
    {
        public int PatientID { get; set; }
        public System.DateTime DeferProbDateEst { get; set; }
        public string DeferProb { get; set; }
        public string DeferProbRatforDefer { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
