//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervention
    {
        public int PatientID { get; set; }
        public System.DateTime InterventDate { get; set; }
        public string Intervent { get; set; }
        public string InterventRepStaff { get; set; }
        public string InterventOften { get; set; }
        public string InterventMet { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
