//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_problem_list
    {
        public int PatientID { get; set; }
        public int MedProbID { get; set; }
        public Nullable<System.DateTime> MedProbDateEst { get; set; }
        public string MedProb { get; set; }
        public string MedProbChronStab { get; set; }
        public Nullable<System.DateTime> MedProbDateChange { get; set; }
        public string MedProbResolved { get; set; }
        public string MedProbDC { get; set; }
        public string MedProbDefer { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
