//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class psychiatric_problem_list
    {
        public int PatientID { get; set; }
        public int PsychProbID { get; set; }
        public Nullable<System.DateTime> PsychProbDateEst { get; set; }
        public string PsychProb { get; set; }
        public string PsychProbChronStab { get; set; }
        public Nullable<System.DateTime> PsychProbDateChange { get; set; }
        public string PsychProbResolved { get; set; }
        public string PsychProbDC { get; set; }
        public string PsychProbDefer { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
