//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class short_term_goals
    {
        public int PatientID { get; set; }
        public int ShortGoalID { get; set; }
        public Nullable<System.DateTime> ShortGoalDate { get; set; }
        public string ShortGoal { get; set; }
        public Nullable<System.DateTime> ShortGoalTargDate { get; set; }
        public Nullable<System.DateTime> ShortGoalNewTargDate { get; set; }
        public string ShortGoalMet { get; set; }
        public string ShortGoalNotMet { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
