//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class substance_abuse
    {
        public int PatientID { get; set; }
        public string SubUsedName { get; set; }
        public string SubUsedStartAge { get; set; }
        public string SubUsedFreqUse90 { get; set; }
        public string SubUsedAmtUsed { get; set; }
        public string SubUsedMethod { get; set; }
        public string SubUsedDuration { get; set; }
        public string SubUsedPrdAbstin { get; set; }
    
        public virtual patient_admission patient_admission { get; set; }
    }
}
